<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="{SITE_DESCRIPTION} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">        
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-envelope-o"></i> &nbsp; Configurações &nbsp;
                            <i class="fa fa-angle-right"></i> &nbsp; E-mail e SMTP
                        </h5>
                    </div>
                    <p class="well well-xs pad-10 fadeables" data-time="10000" id="elm-01">
                        <small>
                            <i class="fa fa-life-ring"></i> 
                            Configurações de e-mail para envio autenticado!
                        </small>
                    </p>                      
                    <div class="panel-body">

                        <div class="tab-content">
                            <div id="novo">
                                <form action="{BASEURI}/painel/configuracao/email/atualizar/"  role="form" method="post" id="form-smtp" >
                                    <div class="form-group well well-sm">
                                        <label for="smtp_host">Endereço SMTP (host)</label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> ex: mail.site.com.br</small>
                                        <input type="text" name="smtp_host" id="smtp_host" class="form-control"
                                               placeholder="Informe o endereço de smtp ex: mail.site.com.br"  value="<?= $this->smtp->smtp_host ?>"/>
                                    </div>

                                    <div class="form-group well well-sm">
                                        <label for="smtp_port">Porta SMTP</label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> ex: 587, 25.</small>                                                                                                                                                                
                                        <input type="text" name="smtp_port" id="smtp_port" class="form-control" 
                                               placeholder="Informe a porta smtp ex: 587 ou 25" value="<?= $this->smtp->smtp_port ?>"/> 
                                    </div>

                                    <div class="form-group well well-sm">
                                        <label for="smtp_user">Conta de e-mail  </label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> ex: contato@site.com.br.</small>                                                                                                                        
                                        <input type="email" name="smtp_user" id="smtp_user" class="form-control" 
                                               placeholder="Informe a conta de e-mail para contato" value="<?= $this->smtp->smtp_user ?>"/> 
                                    </div>

                                    <div class="form-group well well-sm">
                                        <label for="smtp_from">Nome de exibição da Conta </label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> ex: Depto. Financeiro.</small>                                                                                
                                        <input type="text" name="smtp_from" id="smtp_from" class="form-control" 
                                               placeholder="Informe o nome para a conta" value="<?= $this->smtp->smtp_from ?>"/> 
                                    </div>

                                    <div class="form-group well well-sm">
                                        <label for="cliente_email">Senha da conta de e-mail</label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> Deve ser a senha correta da conta em questão.</small>                                                                                 
                                        <input type="password" name="smtp_pass" id="smtp_pass" class="form-control" 
                                               placeholder="Informe a senha da conta de e-mail"/> 
                                    </div>


                                    <div class="form-group well well-sm">
                                        <label for="smtp_bcc">Receber Cópia:</label>
                                        <small class="pull-right"><i class="fa fa-info-circle"></i> ex: supervisor@site.com.br.</small>                                                                                 
                                        <input type="email" name="smtp_bcc" id="smtp_user" class="form-control" 
                                               placeholder="Informe a conta de e-mail para receber cópia oculta" value="<?= $this->smtp->smtp_bcc ?>"/> 
                                    </div>

                                    <div>
                                        <p class="text-center">
                                            <button type="submit" class="btn btn-primary" id="btn-add-update">
                                                <i class="fa fa-refresh"></i>
                                                Atualizar Configurações
                                            </button>
                                        </p>
                                    </div>
                                </form>      
                            </div>
                        </div>
                    </div>                
                </div>
            </div>
            <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
            <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
            <script src="assets/js/admin/main.js" type="text/javascript"></script>
            <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>
            <script src="assets/vendor/jquery.mask.min.js" type="text/javascript"></script>
            <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
            <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">     
            <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>   
            <script>
                $(function () {
                    $('#form-smtp').on('submit', function () {
                        $('#btn-add-update').html('<i class="fa fa-refresh fa-spin"></i> Configurando, aguarde...');
                        var url = '{BASEURI}/painel/configuracao/email/atualizar/';
                        var dados = $('#form-smtp').serialize();
                        $.post(url, {dados: dados}, function (d) {
                            //
                        });
                        setTimeout(function () {
                            var url = '{BASEURI}/contato/testar/';
                            $.post(url, {}, function (data) {
                                if (data == 0) {
                                    $('#btn-add-update').addClass('btn-primary').removeClass('btn-danger').html('<i class="fa fa-refresh fa-spin"></i> Configuração Passou... testando');
                                    setTimeout(function () {
                                        $('#btn-add-update').html('<i class="fa fa-refresh fa-spin"></i> Teste Passou, gravando...');
                                    }, 3500);
                                    setTimeout(function () {
                                        $('#btn-add-update').html('<i class="fa fa-thumbs-up"></i> Atualizado com Sucesso');
                                    }, 3500);
                                    setTimeout(function () {
                                        $('#btn-add-update').html('<i class="fa fa-send-o"></i> Atualizar Configurações');
                                    }, 6000);
                                } else {
                                    $('#btn-add-update').removeClass('btn-primary').addClass('btn-danger').html('<i class="fa fa-refresh"></i> Dados Incorretos - Falha na Configuração SMTP');
                                    _alert_error('<p><i class="glyphicon glyphicon-warning-sign"></i> Confirme os dados do Servidor SMTP com seu Host e tente novamente!</p>');
                                }
                                return false;
                            });
                        }, 3500);
                        return false;
                    });
                });
            </script>
    </body>
</html>