<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="{SITE_DESCRIPTION} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">        
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">        
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">      
        <link href="assets/vendor/fakeinput/fakeinput.css" rel="stylesheet" type="text/css">      
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!-- <link href="assets/css/admin/tabs.css" rel="stylesheet"> -->
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-search"></i> &nbsp; Integração Redes Sociais  &nbsp;
                            <span id="hsp_produto_nome" class="hide">
                                <i class="fa fa-angle-right"></i> 
                            </span>
                        </h5>
                    </div>
                    <p class="well well-xs pad-10 fadeables" data-time="10000" id="elm-01">
                        <small>
                            <i class="fa fa-life-ring"></i> 
                            Informe os perfis das redes sociais de sua empresa.
                        </small>
                    </p>  
                    <div class="panel-body">
                        <div class="tab-content">
                            <form action="{BASEURI}/painel/configuracao/social/atualizar/" method="post" role="form" id="form-seo">

                                <p class="alert alert-block alert-custom">
                                    <i class="fa fa-line-chart"></i>
                                    Redes Sociais
                                </p>

                                <div class="well well-sm">
                                    <div class="form-group has-feedback">
                                        <label class="control-label">Facebook</label>
                                        <span class="pull-right">
                                            <a href="http://facebook.com" target="new">
                                                <i class="fa fa-external-link"></i> criar conta
                                            </a>
                                        </span>
                                        <input type="text" name="social_facebook" id="social_facebook" value="<?= $this->social->social_facebook ?>"
                                               class="form-control" placeholder="Informe o link do perfil ou fanpage no facebook" />
                                    </div>

                                    <div class="form-group has-feedback">
                                        <label class="control-label">Twitter</label>
                                        <span class="pull-right">
                                            <a href="http://twitter.com" target="new">
                                                <i class="fa fa-external-link"></i> criar conta
                                            </a>
                                        </span>
                                        <input type="text" name="social_twitter" id="social_twitter" value="<?= $this->social->social_twitter ?>"
                                               class="form-control" placeholder="Informe o perfil do twitter" />
                                    </div>

                                    <div class="form-group has-feedback">
                                        <label class="control-label">Instagram</label>
                                        <span class="pull-right">
                                            <a href="http://instagram.com" target="new">
                                                <i class="fa fa-external-link"></i> criar conta
                                            </a>
                                        </span>
                                        <input type="text" name="social_instagram" id="social_instagram" value="<?= $this->social->social_instagram ?>"
                                               class="form-control" placeholder="Informe o perfil do instagram" />
                                    </div>

                                    <div class="form-group has-feedback">
                                        <label class="control-label">Google Plus</label>
                                        <span class="pull-right">
                                            <a href="http://plus.google.com" target="new">
                                                <i class="fa fa-external-link"></i> criar conta
                                            </a>
                                        </span>
                                        <input type="text" name="social_plus" id="social_plus" value="<?= $this->social->social_plus ?>"
                                               class="form-control" placeholder="Informe o perfil do google plus" />
                                    </div>

                                    <div class="form-group has-feedback">
                                        <label class="control-label">Linkedin</label>
                                        <span class="pull-right">
                                            <a href="http://linkedin.com" target="new">
                                                <i class="fa fa-external-link"></i> criar conta
                                            </a>
                                        </span>
                                        <input type="text" name="social_linkedin" id="social_linkedin" value="<?= $this->social->social_linkedin ?>"
                                               class="form-control" placeholder="Informe o perfil do linkedin" />
                                    </div>

                                </div>

                                <p class="text-center">
                                    <button type="submit" class="btn btn-primary" id="btn-add-update"><i class="fa fa-refresh"></i>
                                        <span>Atualizar Configurações</span></button>
                                </p>
                            </form>                                
                        </div>                
                    </div>
                </div>
            </div>
        </div>

        <script type="text/javascript" src="assets/vendor/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="assets/js/admin/main.js"></script>
        <script type="text/javascript" src="assets/vendor/notify/js/notifIt.js"></script>
        <script type="text/javascript" src="assets/js/admin/configuracao_site.js"></script>       
        <script src="assets/vendor/fakeinput/fakeinput.js" type="text/javascript"></script>
        <!--controller actions -->
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>		
        <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>
    </body>
</html>
