<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="{SITE_DESCRIPTION} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">        
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">   
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!-- <link href="assets/css/admin/tabs.css" rel="stylesheet"> -->
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-picture-o"></i> &nbsp; Mídias &nbsp;
                            <i class="fa fa-angle-right"></i> Galerias
                        </h5>
                    </div>
                    <p class="well well-xs pad-10 fadeables" data-time="10000" id="elm-01">
                        <small>
                            <i class="fa fa-arrows"></i> 
                            Você pode alterar a ordem de listagem das galerias arrando-as nas posições desejadas!
                        </small>
                    </p>  
                    <div class="panel-body">

                        <p class="text-right">
                            <a href="#lista" role="tab" data-toggle="tab" id="a-tab-lista" class="btn btn-primary hide btn-add-novo">
                                <i class="fa fa-bars"></i>  Listar Galerias
                            </a>
                            <a href="#novo" role="tab" data-toggle="tab" id="a-tab-edit" class="btn btn-primary"> 
                                <i class="fa fa-plus-circle"></i> Nova Galeria
                            </a>
                        </p>
                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="lista">
                                <?php if (is_array($this->data)): ?>                              
                                    <table class="table table-striped" id="table-list">
                                        <thead>
                                            <tr>
                                                <th width="60">ID</th>
                                                <th>Galeria</th>
                                                <th>Categoria</th>
                                                <th width="200"><i class="fa fa-cog"></i></th>
                                            </tr>
                                        </thead>
                                        <tbody class="dragger">
                                            <?php if (is_array($this->data)): ?>
                                                <?php foreach ($this->data as $p): ?>
                                                    <tr id="li_<?= $p->galeria_id; ?>">
                                                        <td class="td-id"><?= $p->galeria_id; ?></td>
                                                        <td class="td-nome"><?= $p->galeria_nome; ?></td>
                                                        <td class="td-nome"><?= $p->gcategoria_nome; ?></td>
                                                        <td class="td-ctrl">
                                                            <a href="{BASEURI}/painel/galeria/foto/<?= $p->galeria_id; ?>/" class="btn btn-primary btn-sm tip" title="fotos"><i class="fa fa-picture-o"></i></a>
                                                            <a href="{BASEURI}/painel/galeria/video/<?= $p->galeria_id; ?>/"  class="btn btn-primary btn-sm tip" title="vídeos"><i class="fa fa-youtube-play"></i></a>
                                                            <button type="button" class="btn btn-primary btn-sm tip btn-edit" id="<?= $p->galeria_id; ?>" name="<?= $p->galeria_nome; ?>" title="editar"><i class="fa fa-edit"></i></button>
                                                            <button type="button" class="btn btn-danger btn-sm tip btn-remove" title="remover" id="<?= $p->galeria_id; ?>"><i class="fa fa-trash-o"></i></button>
                                                        </td>
                                                    </tr>
                                                <?php endforeach; ?>                          
                                            <?php endif; ?>                          
                                        </tbody>
                                    </table>
                                    <div class="text-center">
                                        {PAGINACAO}
                                    </div>
                                <?php else: ?>                          
                                    <p class="well well-sm">
                                        <i class="fa fa-info-circle"></i> 
                                        Você ainda não cadastrou nenhuma galeria!
                                    </p>
                                <?php endif; ?>                          
                            </div>
                            <div class="tab-pane fade" id="novo">
                                <form action="{BASEURI}/painel/galeria/atualizar/" class="form-inlines" role="form" method="post" id="form-galeria">


                                    <div class="well well-sm">
                                        <label>Categoria da Galeria &nbsp; &nbsp;  &nbsp;   &nbsp; 
                                            <a href="{BASEURI}/painel/gcategoria/" class="badge text-default">criar nova</a>
                                        </label>                                
                                        <span class="pull-right text-muted hidden-sm hidden-xs">
                                            <small>
                                                <i class="fa fa-question-circle"></i> 
                                                A vinculação da notícia com uma categoria é opcional.                                        
                                            </small>
                                        </span>
                                        <select name="galeria_gcategoria" id="galeria_gcategoria" class="form-control">
                                            <option value="">Vincular categoria...</option>
                                            <?php foreach ($this->categorias as $c): ?>                                    
                                                <option value="<?= $c->gcategoria_id ?>"><?= $c->gcategoria_nome ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>

                                    <div class="well well-sm">
                                        <div class="form-groups has-feedback">
                                            <label class="control-label">Nome da Galeria &nbsp;</label>
                                            <input type="text" name="galeria_nome" id="galeria_nome" class="form-control" placeholder="Informe o nome da galeria" />
                                            <input type="hidden" name="galeria_id" id="galeria_id"  />
                                        </div>
                                    </div>
                                    <div class="well well-sm">
                                        <div class="form-groups has-feedback">
                                            <label class="control-label">Descrição da Galeria &nbsp;</label>
                                            <textarea type="text" name="galeria_desc" id="galeria_desc"
                                                      class="form-control summernote" placeholder="Descrição da galeria">
                                            </textarea>
                                        </div>
                                    </div>

                                    <button type="submit" class="btn btn-primary" id="btn-add-update"><i class="fa fa-check-circle-o"></i> <span>Cadastrar</span></button>
                                    <button type="button" class="btn btn-danger" id="btn-add-update-cancel"><i class="fa fa-times-circle-o"></i> Cancelar</button>                                    
                                </form>                                
                            </div>                
                        </div>                
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="ModalRemove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        <h4 class="modal-title" id="myModalLabel">Remover Galeria</h4>
                    </div>
                    <div class="modal-body">
                        <h4>Atenção!</h4>
                        <p>
                            Você está prestes à excluir um registro de forma permanente.<br />
                            Deseja realmente executar este procedimento?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle-o"></i> Cancelar</button>
                        <button type="button" class="btn btn-danger" id="btn-confirm-remove"><i class="fa fa-check-circle-o"></i> Confirmar</button>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="assets/vendor/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="assets/vendor/jquery-ui.min.js"></script>
        <script type="text/javascript" src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="assets/js/admin/main.js"></script>
        <!-- summernote plugin -->
        <link rel="stylesheet" href="plugins/summernote/dist/summernote.css">
        <link rel="stylesheet" href="plugins/summernote/dist/summernote-bs3.css">
        <script type="text/javascript" src="plugins/summernote/dist/summernote.js"></script>
        <script type="text/javascript" src="plugins/summernote/lang/summernote-pt-BR.js"></script>
        <!--controller actions -->
        <script type="text/javascript" src="assets/js/admin/galeria.js"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>
        <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
        <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>
        <!--<script type="text/javascript">_alert_help('<i class="fa fa-arrows"></i> Você pode alterar a ordem de listagem das galerias arrando-as nas posições desejadas!', 5000);</script>-->
    </body>
</html>