<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="{SITE_DESCRIPTION} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">        
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">   
        <link href="assets/css/admin/dropzone.css" rel="stylesheet">        
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!-- <link href="assets/css/admin/tabs.css" rel="stylesheet"> -->
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">
                <div class="navbar-fixed-top navbar-inverse hide toolbar-save bg-primary opacity-8">
                    <div class="container-fluid">
                        <div class="pull-left">
                            <button class="btn btn-primary">
                                <i class="fa fa-picture-o"></i> Mídias 
                                <i class="fa fa-angle-right"></i> Galerias
                                <i class="fa fa-angle-right"></i> {GALERIA_CATEGORIA}
                                <i class="fa fa-angle-right"></i> {GALERIA_NOME}
                                <i class="fa fa-angle-right"></i> Fotos
                            </button>
                        </div>
                        <div class="pull-right">
                            <a href="{BASEURI}/painel/galeria/" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Voltar para Galerias</a>
                            <button class="btn btn-primary go-to-top"><i class="fa fa-chevron-up"></i> Voltar ao Top</button>
                        </div>
                    </div>
                </div>

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-picture-o"></i> Mídias 
                            <i class="fa fa-angle-right"></i> Galerias
                            <i class="fa fa-angle-right"></i> {GALERIA_CATEGORIA}                            
                            <i class="fa fa-angle-right"></i> {GALERIA_NOME}
                            <i class="fa fa-angle-right"></i> Fotos
                        </h5>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="text-right">
                                    <button id="btn-upload" class="btn btn-primary" type="button"> 
                                        <i class="fa fa-cloud-upload"></i> Enviar Fotos
                                    </button>
                                </p>
                            </div>
                            <div class="col-md-6">
                                <p  class="pull-right">
                                    <button id="btn-remove-selecao" class="btn btn-danger" type="button"> 
                                        <i class="fa fa-trash-o"></i>
                                    </button>
                                </p>
                            </div>
                        </div>

                        <br />
                        <div class="tab-content">
                            <div class="tab-pane fade in active galeria-foto-thumb">                                
                                <div class="dragger_foto col-md-12">
                                    <p> </p>
                                    <?php if (is_array($this->fotos)): ?>
                                        <?php foreach ($this->fotos as $f): ?>
                                            <div class="col-md-2" id="d_<?= $f->foto_id ?>">
                                                <div class="thumbnail">
                                                    <img src="{BASEURI}/thumb.php?h=150&src=midia/foto/<?= $f->foto_url ?>" class="img-responsive"  style="height: 120px;cursor: move" title="arraste a imagem para mudar a ordem da galeria"/>
                                                    <div class="caption">
                                                        <p id="f_<?= $f->foto_id ?>"><?= $f->foto_nome ?> &nbsp;</p>
                                                        <p align="center">
                                                            <button class="btn btn-sm btn-primary foto-zoom" type="button" 
                                                                    data-url="{BASEURI}/thumb.php?h=350&src=midia/foto/<?= $f->foto_url ?>"
                                                                    data-nome="<?= $f->foto_nome ?>"
                                                                    data-pos="<?= $f->foto_pos ?>"
                                                                    id="<?= $f->foto_id ?>"
                                                                    >
                                                                <i class="fa fa-pencil-square-o"></i>
                                                            </button>
                                                            <span class="button-checkbox">
                                                                <button type="button" class="btn btn-sm btn-danger btn-foto-remove" data-color="danger"><i class="fa fa-trash-o"></i></button>
                                                                <input type="checkbox" name="foto_id_drop[]" value="<?= $f->foto_id ?>" data-url="<?= $f->foto_url ?>" class="hidden checkbox-remove" />
                                                            </span>
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>   
                                    <?php endif; ?>   
                                </div>
                                <div class="text-center">
                                    {PAGINACAO}
                                </div>
                            </div>
                        </div>                
                    </div>
                </div>
            </div>
        </div>


        <div class="modal fade" id="ModalRemove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        <h4 class="modal-title" id="myModalLabel">Remover Fotos</h4>
                    </div>
                    <div class="modal-body">
                        <h4>Atenção!</h4>
                        <p>
                            Você está prestes à excluir um registro de forma permanente.<br />
                            Deseja realmente executar este procedimento?
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle-o"></i> Cancelar</button>
                        <button type="button" class="btn btn-danger" id="btn-confirm-remove"><i class="fa fa-check-circle-o"></i> Confirmar</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="ModalUpload" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        <h4 class="modal-title" id="myModalLabel">Enviar Fotos para Galeria</h4>
                    </div>
                    <div class="modal-body">

                        <form action="{BASEURI}/painel/galeria/upload/" class="dropzone" id="meudrop"
                              style="min-height: 400px !important;border: 4px dashed #DDD">
                            <div class="fallback col-md-8">
                                <input name="file" type="file" multiple />
                            </div>
                        </form> 

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default hide" id="btn-upload-complete" data-dismiss="modal">
                            <i class="fa fa-cloud-upload"></i> 
                            Enviando, aguarde...
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="ModalZoom" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lgs">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                        <h4 class="modal-title" id="myModalLabel">Zoom</h4>
                    </div>
                    <div class="modal-body">
                        <div class="text-center">
                            <span id="foto_spot"></span>
                        </div>
                        <br />
                        <div class="form-group">
                            <div class="control-group" id="fields">
                                <label class="control-label" for="field1">Informe uma lengenda para a foto:</label>
                                <div class="controls"> 
                                    <div class="entry input-group ">
                                        <input type="text" id="foto_nome" name="foto_nome" class="form-control" placeholder="Informe uma Legenda para esta foto" />
                                        <input type="hidden" id="foto_id" name="foto_id" />
                                        <span class="input-group-btn">
                                            <button type="button" class="btn btn-primary" id="btn-update-foto">
                                                <i class="fa fa-refresh"></i> Atualizar
                                            </button>                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-sm btn-default hide" data-dismiss="modal">
                            <i class="fa fa-times-circle-o"></i> Fechar
                        </button>
                    </div>
                </div>
            </div>
        </div>        

        <script type="text/javascript" src="assets/vendor/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="assets/vendor/jquery-ui.min.js"></script>
        <script type="text/javascript" src="assets/js/admin/main.js"></script>
        <script type="text/javascript" src="assets/js/admin/checkbox.js"></script>
        <script type="text/javascript" src="assets/js/admin/galeria.js"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>
        <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
        <script src="assets/vendor/dropzone.js"></script>
        <script type="text/javascript">
            $(function () {
                $('#a-tab-lista').tab('show');
                Dropzone.autoDiscover = false;
                $("#meudrop").dropzone({
                    url: "{BASEURI}/painel/galeria/upload/",
                    accept: function (file, done) {
                        $("#btn-upload-complete").removeClass('hide').show();
                        done();
                    },
                    maxFilesize: 5, // MB
                    complete: function (file) {
                        rs = $.parseJSON(file.xhr.response)
                        fsize = Math.round(file.size / 1024 / 10.24) / 100;
                        if (fsize > 5) {
                            _alert_error_time('<p><i class="fa fa-warning-sign"></i> Arquivo muito grande. O tamanho máximo permitido é: 5MB</p>', 7000);
                        }
                        if (rs.status == 'error') {
                            _alert_error_time('<p><i class="fa fa-warning-sign"></i> ' + rs.error + '</p>', 12000);
                        }
                        if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                            $("#btn-upload-complete").removeClass('btn-default').addClass('btn-success').html('<i class="glyphicon glyphicon-ok-circle"></i>  Envio Concluído');
                        }
                    },
                    sending: function (file, xhr, formData) {
                        formData.append("galeria_id", "{GALERIA_ID}");
                    },
                    totaluploadprogress: function () {
                        //console.log('terminei agora...')
                    }
                    //dictRemoveFile: 'remover',
                    //dictCancelUpload: 'cancelar',
                    //addRemoveLinks: true,
                    //autoProcessQueue: false
                });
            });
        </script>      
        <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>
    </body>
</html>