<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_TITLE}">
        <meta name="author" content="{SITE_TITLE} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/css/admin/main.css" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12  pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12  pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Olá {USER_NOME}, seja bem-vindo!</h3>
                    </div>
                    <div class="panel-body">

                        <div class="row morris">
                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                <H4 class="text-center">ACESSOS NESTE MÊS</H4>
                                <div id="chart_div1" style="width: 100%; height: 400px;"></div>
                                <br /><br /><br /><br />
                            </div>
                            <!--
                            <div class="col-md-6 col-lg-6 col-sm-6 col-xs-6">
                                <H4 class="text-center">CADASTROS DO SISTEMA</H4>
                                <div id="chart_div5" style="width: 100%; height: 400px;"></div>
                            </div>
                            -->

                            <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                                <H4 class="text-center">EMPRESAS MAIS VISITADAS</H4>
                                <div id="chart_div6" style="width: 100%; height: 400px;"></div>
                            </div>
                        </div>


                    </div>
                </div>                
            </div>                
        </div>
        <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
        <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="assets/js/admin/main.js" type="text/javascript"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>

        <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
        <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
        <script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>        

        <script>
                    /*
                     Morris.Donut({
                     element: 'chart_div5',
                     colors: ['#3FB618', '#9954BB', '#555', '#3980B5','#E15119'],
                     data: [
                     {label: "Produtos", value: <?= $this->data['produto']->click ?>},
                     {label: "Páginas", value: <?= $this->data['pagina']->click ?>},
                     {label: "Serviço", value: <?= $this->data['servico']->click ?>},
                     {label: "Fotos", value: <?= $this->data['foto']->click ?>},
                     {label: "Vídeos", value: <?= $this->data['video']->click ?>}
                     ],
                     gridTextSize: 8,
                     resize: true
                     });
                     */
                    Morris.Bar({
                    element: 'chart_div6',
                            //stacked: true,
                            barColors: ['#3980B5', '#3FB618', '#555'],
                            data: [
<?php foreach ($this->data['cliente'] as $c): ?>
                                {y: '<?= $c->cliente_empresa ?>', a: <?= $c->cliente_click_uniq ?>, b: <?= $c->cliente_click_view ?>},
<?php endforeach; ?>
                            ],
                            xkey: 'y',
                            ykeys: ['a', 'b'],
                            labels: ['Acessos Únicos', 'Visualizações'],
                            barRatio: 0.4,
                            xLabelAngle: 35,
                            hideHover: 'auto'
                    });
                    Morris.Line({
                    element: 'chart_div1',
                            data: [
<?php foreach ($this->data['acesso'] as $c): ?>
                                {y: '<?= date('Y-m-d', strtotime($c->acesso_data)) ?>', a: <?= $c->acesso_click ?>},
<?php endforeach; ?>
                            ],
                            xkey: 'y',
                            ykeys: ['a'],
                            labels: ['Acessos']
                    });
        </script>
    </body>
</html>