<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_TITLE}">
        <meta name="author" content="{SITE_TITLE} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/css/admin/main.css" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12  pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12  pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-sliders"></i> EDITOR AVANÇADO DE MÓDULOS</h3>
                    </div>
                    <div class="panel-body">
                        <h4 class="alert alert-danger">
                            Atenção!<br />
                            Qualquer alteração incorreta causará o mal funcionamento do site! <br />
                            Se não tem certeza do que está fazendo, não altere nada!
                        </h4>
                        <select class="form-control" name="sel" id="sel" onchange="window.location = this.value">
                            {_OPTIONS_}
                        </select>
                        <br /><br />
                        <form action="{BASEURI}/painel/modulo/save/" method="post">
                            <textarea class="form-control" name="modulo_config_options" rows="8" style="width:100%">{_MODCONF_}</textarea>
                            <input type='hidden' name='modulo_id' value='{_MODULO_}'>
                            <br /><br />
                            <button class="btn btn-primary" type="submit">Save!</button>
                        </form>
                    </div>
                </div>
            </div>                
        </div>                
    </div>
    <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
    <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="assets/js/admin/main.js" type="text/javascript"></script>
    <script type="text/javascript">setMenuAtivo('modulo');</script>
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>        
    <script type="text/javascript">
                            $('#sel').on('change', function () {
                                window.location = '{BASEURI}/painel/modulo/' + $('#sel').val();
                            });
                            $("#sel").val('{_MODULO_}');
    </script>
</body>
</html>