<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/vendor/fakeinput/fakeinput.css" rel="stylesheet" type="text/css"> 
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">          
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">

                <div class="navbar-fixed-bottom navbar-inverse hide toolbar-save bg-primary opacity-8">
                    <div class="container-fluid">
                        <div class="pull-left">
                            <button class="btn btn-primary">
                                <i class="fa fa-cog fa-spin fa-1x"></i>
                            </button>
                        </div>
                        <div class="pull-right">
                            <button id="trig-submit" type="button" class="btn btn-primary"><i class="fa fa-check-circle-o"></i> Gravar</button>                            
                            <a href="{BASEURI}/painel/noticia/" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Voltar para Notícias</a>
                            <button class="btn btn-primary go-to-top"><i class="fa fa-chevron-up"></i> Voltar ao Topo</button>
                        </div>
                    </div>
                </div>

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-newspaper-o"></i>  &nbsp; Notícias   &nbsp;
                            <i class="fa fa-angle-right"></i> Nova Notícia
                        </h5>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="{BASEURI}/painel/noticia/incluir/" method="post" id="form-noticia" 
                              enctype="multipart/form-data">
                            <div class="form-group well well-sm">
                                <label>Categoria da Notícias &nbsp; &nbsp;  &nbsp;   &nbsp; 
                                    <a href="{BASEURI}/painel/ncategoria/" class="badge text-default">criar nova</a>
                                </label>                                
                                <span class="pull-right text-muted hidden-sm hidden-xs">
                                    <small>
                                        <i class="fa fa-question-circle"></i> 
                                        A vinculação da notícia com uma categoria é opcional.                                        
                                        <a  href="javascript:void(0);" class="link-help"> 
                                            (Precisa de ajuda? clique aqui)
                                        </a>
                                    </small>
                                </span>
                                <select name="noticia_ncategoria" id="noticia_ncategoria" class="form-control">
                                    <option value="">Vincular à uma categoria...</option>
                                    <?php foreach ($this->categorias as $c): ?>                                    
                                        <option value="<?= $c->ncategoria_id ?>"><?= $c->ncategoria_nome ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="">
                                <div class="form-group has-feedback well well-sm">
                                    <label>Título da Notícia</label>
                                    <input type="text" class="form-control" name="noticia_titulo" id="noticia_titulo" placeholder="Informe o título da notícia" />
                                </div>
                            </div>


                            <div class="form-group has-feedback well well-sm">
                                <label>Palavras-chave (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i>  Meta Keywords - Máximo 156 caracteres</small></span>                                
                                <input type="text" class="form-control" name="noticia_meta_keywords" id="noticia_meta_keywords"
                                       value="" placeholder="Informe as palavras-chave da notícia" />
                            </div>                            

                            <div class="form-group has-feedback well well-sm">
                                <label>Descrição breve (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i> Meta Description - Máximo 156 caracteres</small></span>
                                <input type="text" class="form-control" name="noticia_meta_desc" maxlength="156" 
                                       value="" id="noticia_meta_desc" placeholder="Informe uma descrição breve de até 156 caracteres para a notícia" />
                            </div> 

                            <div class="form-group form-inline well well-sm">
                                <label>Foto/Capa da Notícia </label>
                                <div class="fakeipt">
                                    <div class="uploader black">
                                        <input type="text" class="filename" readonly="readonly"/>
                                        <input type="button" name="file" id="file" class="button" value="Selecionar Imagem"/>
                                        <input type="file" name="filedata" size="30"/>
                                    </div>
                                </div>
                            </div>                            

                            <div class="form-group well well-sm">
                                <label>Conteúdo da Notícia</label>
                                <textarea class="summernote"  id="noticia_texto" name="noticia_texto" style="height: 300px;"></textarea>
                            </div>

                            <div class="form-group">
                                <p class="text-right">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-check-circle-o"></i> Gravar</button>
                                    <a href="{BASEURI}/painel/noticia/" class="btn btn-danger"><i class="fa fa-times-circle-o"></i> Cancelar</a>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>                
            </div>

        </div>

        <div class="modal fade" id="ModalHelp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Ajuda</h4>
                    </div>
                    <div class="modal-body">
                        <h4><i class="fa fa-info-circle"></i>  Categoria da Notícias!</h4>
                        <p>
                            Quando você vincula a notícia à uma categoria, sua notícia é exibida no menu 
                            da categoria vinculada.<br /><br />
                            Exemplo de uma categoria: <br />
                            - Investimentos <br/> <br />
                            Exemplo de notícias da categoria investimentos: <br />
                            - notícia 01 <br />
                            - notícia 02 <br />
                            <br />
                            A categoria lhe permite separar em um menu, as notícias de seu site. <br />
                            Este procimento é opcional, você pode criar notícias sem categorias e 
                            elas aparecerão normalmente!
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-thumbs-up"></i> Entendi</button>
                    </div>
                </div>
            </div>
        </div>

        <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js"></script>
        <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
        <!-- BGN summernote plugin -->
        <link rel="stylesheet" href="plugins/summernote/dist/summernote.css">
        <link rel="stylesheet" href="plugins/summernote/dist/summernote-bs3.css">
        <script type="text/javascript" src="plugins/summernote/dist/summernote.js"></script>
        <script type="text/javascript" src="plugins/summernote/lang/summernote-pt-BR.js"></script>
        <!-- END summernote plugin-->
        <script type="text/javascript" src="assets/js/admin/main.js"></script>
        <script src="assets/vendor/fakeinput/fakeinput.js" type="text/javascript"></script>
        <script src="assets/js/admin/noticia.js" type="text/javascript"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>      
        <script type="text/javascript">summerNote();</script>		
    </body>
</html>


