<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">        
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">		
        <link href="assets/css/admin/main.css" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">

                <div class="navbar-fixed-bottom navbar-inverse hide toolbar-save bg-primary opacity-8">
                    <div class="container-fluid">
                        <div class="pull-left">
                            <button class="btn btn-primary">
                                <i class="fa fa-cog fa-spin fa-1x"></i>
                            </button>
                        </div>
                        <div class="pull-right">
                            <button class="btn btn-primary go-to-top"><i class="fa fa-chevron-up"></i> Voltar ao Topo</button>
                            <button class="btn btn-primary" id="trig-submit"><i class="fa fa-refresh"></i> Atualizar</button>
                            <a href="{BASEURI}/painel/pagina/" class="btn btn-primary"><i class="fa fa-times-circle-o"></i> Cancelar</a>
                            <a href="{BASEURI}/painel/pagina/" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Voltar</a>                            
                        </div>
                    </div>
                </div>


                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-file-text"></i> Conteúdo &nbsp;
                            <i class="fa fa-angle-right"></i> Editar Página
                            <?php if ($this->data->area_nome != ""): ?>
                                <i class="fa fa-angle-right"></i> <?= $this->data->area_nome; ?>
                            <?php endif; ?>
                            <i class="fa fa-angle-right"></i> <?= $this->data->pagina_nome; ?>
                        </h5>
                    </div>
                    <div class="panel-body">

                        <form id="form-pagina" role="form" action="{BASEURI}/painel/pagina/atualizar/" method="post">
                            <div class="form-group well well-sm">
                                <label>Área da Página &nbsp; &nbsp;  &nbsp;   &nbsp; 
                                    <a href="{BASEURI}/painel/area/" class="badge text-default">criar nova</a>
                                </label>                                
                                <span class="pull-right text-muted">
                                    <small>
                                        <i class="fa fa-question-circle"></i> 
                                        A vinculação da página com uma área é opcional.                                        
                                        <a  href="javascript:void(0);" class="link-help"> 
                                            (Precisa de ajuda? clique aqui)
                                        </a>
                                    </small>
                                </span>                              
                                <select name="pagina_area" id="pagina_area" class="form-control">
                                    <option value="">Vincular à uma área...</option>
                                    <?php foreach ($this->areas as $a): ?>                                    
                                        <option value="<?= $a->area_id ?>"><?= $a->area_nome ?></option>
                                    <?php endforeach; ?>  
                                </select>
                            </div>

                            <div class="form-group well well-sm">
                                <label>Título da Página</label>
                                <input type="text" class="form-control" required name="pagina_nome" id="pagina_nome" value="<?= $this->data->pagina_nome; ?>" placeholder="Informe o título da página" />
                            </div>


                            <div class="form-group has-feedback well well-sm">
                                <label>Palavras-chave (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i>  Meta Keywords - Máximo 156 caracteres</small></span>                                
                                <input type="text" class="form-control" name="pagina_meta_keywords" id="pagina_meta_keywords" value="<?= $this->data->pagina_meta_keywords; ?>"
                                       placeholder="Informe as palavras-chave da página" />
                            </div>                            

                            <div class="form-group has-feedback well well-sm">
                                <label>Descrição breve (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i> Meta Description - Máximo 156 caracteres</small></span>
                                <input type="text" class="form-control" name="pagina_meta_desc" maxlength="156" value="<?= $this->data->pagina_meta_desc; ?>"
                                       id="pagina_meta_desc" placeholder="Informe uma descrição breve de até 156 caracteres para a página" />
                            </div> 

                            <div class="form-group well well-sm">
                                <label>&nbsp;</label>
                                <textarea class="summernote" name="pagina_texto" id="pagina_texto" style="min-height:350px;"><?= $this->data->pagina_texto; ?></textarea>
                            </div>

                            <div class="form-group">
                                <p class="well well-sm pad-6">
                                    Link da paǵina: {BASEURI}/pagina/<?= $this->data->area_url; ?>/<?= $this->data->pagina_url; ?>/
                                </p>
                            </div>

                            <div class="form-group">
                                <p class="text-right">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-refresh"></i> Atualizar</button>
                                    <a href="{BASEURI}/painel/pagina/" class="btn btn-danger"><i class="fa fa-times-circle-o"></i> Cancelar</a>
                                </p>
                            </div>
                            <input type="hidden" name="pagina_id" id="pagina_id" value="<?= $this->data->pagina_id; ?>"  />
                        </form>

                    </div>
                </div>                
            </div>

        </div>


        <div class="modal fade" id="ModalHelp" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="myModalLabel">Ajuda</h4>
                    </div>
                    <div class="modal-body">
                        <h4><i class="fa fa-info-circle"></i>  Área da Página!</h4>
                        <p>
                            Quando você vincula a página à uma área, sua página é exibida no menu 
                            da área vinculada.<br /><br />
                            Exemplo de uma área: <br />
                            - Projetos <br/> <br />
                            Exemplo de páginas da área Projetos: <br />
                            - Projeto 01 <br />
                            - Projeto 02 <br />
                            <br />
                            A categoria lhe permite separar em um menu, as páginas de seu site. <br />
                            Este procimento é opcional, você pode criar páginas sem áreas e 
                            elas aparecerão diretamente no menu (ao lado dos menus das áreas cadastradas)!
                        </p>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-thumbs-o-up"></i> Entendi</button>
                    </div>
                </div>
            </div>
        </div>

        <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
        <!-- BGN summernote plugin -->
        <link rel="stylesheet" href="plugins/summernote/dist/summernote.css">
        <link rel="stylesheet" href="plugins/summernote/dist/summernote-bs3.css">
        <script type="text/javascript" src="plugins/summernote/dist/summernote.js"></script>
        <script type="text/javascript" src="plugins/summernote/lang/summernote-pt-BR.js"></script>
        <!-- END summernote plugin-->
        <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
        <script src="assets/js/admin/main.js" type="text/javascript"></script>
        <script src="assets/js/admin/pagina.js" type="text/javascript"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>        
        <script type="text/javascript">summerNote();</script>	        
        <script type="text/javascript">$('#pagina_area').val('<?= $this->data->area_id ?>');</script>        
        <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
        <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>        
    </body>
</html>