<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/vendor/fakeinput/fakeinput.css" rel="stylesheet" type="text/css"> 
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">          
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">


                <div class="navbar-fixed-bottom navbar-inverse hide toolbar-save bg-primary opacity-8">
                    <div class="container-fluid">
                        <div class="pull-left">
                            <button class="btn btn-primary">
                                <i class="fa fa-cog fa-spin fa-1x"></i>
                            </button>
                        </div>
                        <div class="pull-right">
                            <button id="trig-submit" type="button" class="btn btn-primary"><i class="fa fa-check-circle-o"></i> Gravar</button>                            
                            <a href="{BASEURI}/painel/servico/" class="btn btn-primary"><i class="fa fa-chevron-left"></i> Voltar para Serviços</a>
                            <button class="btn btn-primary go-to-top"><i class="fa fa-chevron-up"></i> Voltar ao Topo</button>
                        </div>
                    </div>
                </div>                

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-newspaper-o"></i>  &nbsp; Serviços   &nbsp;
                            <i class="fa fa-angle-right"></i> Novo Serviço
                        </h5>
                    </div>
                    <div class="panel-body">
                        <form role="form" action="{BASEURI}/painel/servico/incluir/" method="post" id="form-servico" 
                              enctype="multipart/form-data">
                            <div class="">
                                <div class="form-group has-feedback well well-sm">
                                    <label>Título do Serviço</label>
                                    <input type="text" class="form-control" name="servico_titulo" id="servico_titulo" placeholder="Informe o título do serviço" />
                                </div>
                            </div>

                            <div class="form-group form-inline well well-sm">
                                <label>Logo do Serviço </label>
                                <div class="fakeipt">
                                    <div class="uploader black">
                                        <input type="text" class="filename" readonly="readonly"/>
                                        <input type="button" name="file" id="file" class="button" value="Selecionar Imagem"/>
                                        <input type="file" name="filedata" size="30"/>
                                    </div>
                                </div>
                            </div>                            

                            <div class="form-group has-feedback well well-sm">
                                <label>Palavras-chave (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i>  Meta Keywords - Máximo 156 caracteres</small></span>                                
                                <input type="text" class="form-control" name="servico_meta_keywords" id="servico_meta_keywords" placeholder="Informe as palavras-chave do serviço" />
                            </div>                            

                            <div class="form-group has-feedback well well-sm">
                                <label>Descrição breve (SEO - Opcional)</label>
                                <span class="pull-right"><small><i class="fa fa-info-circle"></i>  Meta Description -  Máximo 156 caracteres</small></span>
                                <input type="text" class="form-control" name="servico_meta_desc" maxlength="156"
                                       id="servico_meta_desc" placeholder="Informe uma descrição breve de até 156 caracteres para o serviço" />
                            </div>   

                            <div class="form-group well well-sm">
                                <label>Descrição do Serviço</label>
                                <textarea class="summernote"  id="servico_texto" name="servico_texto" style="height: 300px;"></textarea>
                            </div>

                            <div class="form-group">
                                <p class="text-right">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-check-circle-o"></i> Gravar</button>
                                    <a href="{BASEURI}/painel/servico/" class="btn btn-danger"><i class="fa fa-times-circle-o"></i> Cancelar</a>
                                </p>
                            </div>
                        </form>
                    </div>
                </div>                
            </div>
        </div>
        <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
        <script type="text/javascript" src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js"></script>
        <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
        <!-- BGN summernote plugin -->
        <link rel="stylesheet" href="plugins/summernote/dist/summernote.css">
        <link rel="stylesheet" href="plugins/summernote/dist/summernote-bs3.css">
        <script type="text/javascript" src="plugins/summernote/dist/summernote.js"></script>
        <script type="text/javascript" src="plugins/summernote/lang/summernote-pt-BR.js"></script>
        <!-- END summernote plugin-->
        <script type="text/javascript" src="assets/js/admin/main.js"></script>
        <script src="assets/vendor/fakeinput/fakeinput.js" type="text/javascript"></script>
        <script src="assets/js/admin/servico.js" type="text/javascript"></script>
        <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>      
        <script type="text/javascript">summerNote();</script>		
    </body>
</html>


