<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="author" content="{SITE_DESCRIPTION} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">        
        <link href="assets/css/admin/main.css" rel="stylesheet">
        <link href="assets/vendor/fakeinput/fakeinput.css" rel="stylesheet" type="text/css">      
        <link href="assets/vendor/notify/css/notifIt.css" rel="stylesheet" type="text/css">     
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12 pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12 pad-1" id="panel-content">

                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h5 class="no-margin"> 
                            <i class="fa fa-picture-o"></i> &nbsp; Mídias &nbsp;
                            <i class="fa fa-angle-right"></i> Slideshow
                        </h5>
                    </div>
                    <p class="well well-xs pad-10 fadeables" data-time="10000" id="elm-01">
                        <small>
                            <i class="fa fa-arrows"></i>
                            Você pode alterar a ordem de exibição do slideshow arrando para as posições desejadas!
                        </small>
                    </p>                      
                    <div class="panel-body">

                        <p class="text-right">
                            <a href="#lista" role="tab" data-toggle="tab" id="a-tab-lista" class="btn btn-primary btn-sms hide">
                                <i class="fa fa-bars"></i>  Listar Slides
                            </a>
                            <a href="#novo" role="tab" data-toggle="tab" id="a-tab-edit" class="btn btn-primary btn-sms"> 
                                <i class="fa fa-plus-circle"></i> Novo Slide
                            </a>   
                        </p>

                        <div class="tab-content">
                            <div class="tab-pane fade in active" id="lista">
                                <?php if (is_array($this->data)): ?>
                                    <table class="table table-striped tbl-slide-list" id="table-list">
                                        <thead>
                                            <tr>
                                                <th width="60">ID</th>
                                                <th>Slide</th>
                                                <th>Título</th>
                                                <th width="110"><i class="fa fa-cog"></i></th>
                                            </tr>
                                        </thead>
                                        <tbody class="dragger">
                                            <?php foreach ($this->data as $p): ?>
                                                <tr id="tr_<?= $p->slide_id; ?>">
                                                    <td width="70"><?= $p->slide_id; ?></td>
                                                    <td><img src="{BASEURI}/thumb.php?w=200&src=midia/slide/<?= $p->slide_url; ?>" style="" /></td>
                                                    <td><?= $p->slide_titulo; ?></td>
                                                    <td class="td-ctrl">
                                                         <!-- <a href="{BASEURI}/painel/slide/editar/<?= $p->slide_id; ?>/" class="btn btn-primary btn-sm tip" title="editar"><i class="glyphicon glyphicon-edit"></i></a> -->
                                                        <button class="btn btn-primary btn-sm tip btn-edit" title="editar" id="<?= $p->slide_id; ?>" name="<?= $p->slide_titulo; ?>" data-url="<?= $p->slide_url; ?>" data-msg="<?= $p->slide_msg; ?>" data-link="<?= $p->slide_link; ?>">  <i class="fa fa-edit"></i></button>
                                                        <button class="btn btn-danger btn-sm tip btn-remove" title="remover" id="<?= $p->slide_id; ?>" name="<?= $p->slide_titulo; ?>"><i class="fa fa-trash-o"></i></button>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>                          
                                        </tbody>
                                    </table>
                                    <div class="text-center">
                                        {PAGINACAO}
                                    </div>                                
                                <?php else: ?>                          
                                    <p class="well well-sm">
                                        <i class="fa fa-info-circle"></i> 
                                        Você ainda não cadastrou nenhum slide!
                                    </p>
                                <?php endif; ?>    
                            </div>

                            <div class="tab-pane fade" id="novo">
                                <form action="{BASEURI}/painel/slide/upload/" enctype="multipart/form-data"
                                      role="form" method="post" id="form-slide" >

                                    <div class="form-group well well-sm">
                                        <label for="slide_titulo">Título do Banner (opcional)</label>
                                        <input type="text" name="slide_titulo" id="slide_titulo" class="form-control" placeholder="Informe um título breve para o slide" />
                                    </div>
                                    <!--
                                    <div class="form-group well well-sm">
                                        <label for="slide_msg">Mensagem do Slide (opcional)</label>
                                        <input type="text" name="slide_msg" id="slide_msg" class="form-control" placeholder="Informe uma mensagem breve para o slide" />
                                    </div>
                                    -->

                                    <div class="form-group well well-sm">
                                        <label for="slide_link">Link do Banner (opcional)</label>
                                        <input type="text" name="slide_link" id="slide_link" class="form-control" placeholder="Informe um link interno ou externo para o slide" />
                                    </div>

                                    <div class="form-group form-inline well well-sm">
                                        <label>Imagem do Slide (220 x 260 pixels)</label>
                                        <div class="fakeipt">
                                            <div class="uploader black">
                                                <input type="text" class="filename" readonly="readonly"/>
                                                <input type="button" name="file" id="file" class="button" value="Selecionar Imagem"/>
                                                <input type="file" name="filedata" size="30"/>
                                            </div>
                                            <div class="pull-right hide" id="slide-preview">
                                                <img src="{BASEURI}/midia/slide/" class="img-thumbnail" style="margin-top: -25px;width:140px; height: 75px;"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div>
                                        <p>
                                            <button type="submit" class="btn btn-primary" id="btn-add-update"><i class="fa fa-check-circle-o"></i> <span id="btn-add-update-slide">Cadastrar</span></button>
                                            <button type="button" class="btn btn-danger" id="btn-add-update-cancel"><i class="fa fa-times-circle-o"></i> <span>Cancelar</span></button>
                                        </p>
                                    </div>
                                    <input type="hidden" name="slide_id" id="slide_id"  value=""/>
                                    <input type="hidden" name="slide_local" id="slide_local"  value="1"/>
                                </form>      
                            </div>
                        </div>
                    </div>                
                </div>
            </div>
            <div class="modal fade" id="ModalRemove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Fechar</span></button>
                            <h4 class="modal-title" id="myModalLabel">Remover Destaque</h4>
                        </div>
                        <div class="modal-body">
                            <h4>Atenção!</h4>
                            <p>
                                Você está prestes à excluir um registro de forma permanente.<br />
                                Deseja realmente executar este procedimento?
                            </p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times-circle-o"></i> Cancelar</button>
                            <button type="button" class="btn btn-danger" id="btn-confirm-remove"><i class="fa fa-check-circle-o"></i> Confirmar</button>
                        </div>
                    </div>
                </div>
            </div>
            <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
            <script type="text/javascript" src="assets/vendor/jquery-ui.min.js"></script>            
            <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
            <script src="assets/js/admin/main.js" type="text/javascript"></script>
            <script type="text/javascript">setMenuAtivo('{MENU_ATIVO}');</script>
            <script src="assets/js/admin/slide.js" type="text/javascript"></script>
            <script src="assets/vendor/fakeinput/fakeinput.js" type="text/javascript"></script>
            <script src="assets/vendor/notify/js/notifIt.js" type="text/javascript"></script>
            <script type="text/javascript">[FN_ONLOAD]/*executa funcoes js vindas do controller */</script>   
    </body>
</html>