<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_TITLE}">
        <meta name="author" content="{SITE_TITLE} desenvolvido por WEB4ALL">
        <base href="{BASEURI}/" >
        <title>{SITE_TITLE} - Painel Administrativo</title>
        <link href="assets/vendor/bootstrap-3.2.0/css/bootstrap.min.css" rel="stylesheet" type="text/css">
        <link href="assets/vendor/bootstrap-3.2.0/css/{SITE_TEMA}/bootstrap.min.css" rel="stylesheet">
        <link href="assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <link href="assets/css/admin/main.css" rel="stylesheet" type="text/css">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="wrap">
            <?php require_once 'topo_alt.html'; ?> 
            <div class="col-md-2 col-lg-2 col-sm-3 col-xs-12  pad-1" id="side-bar">
                <?php require_once 'menu.phtml'; ?> 
            </div>
            <div class="col-md-10 col-lg-10 col-sm-9 col-xs-12  pad-1" id="panel-content">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title"><i class="fa fa-sliders"></i> ATUALIZAÇÕES DO SISTEMA CMS+</h3>
                    </div>
                    <div class="panel-body">
                        <h4 class="alert alert-danger">
                            Atenção!<br />
                            Antes de realizar quaisquer atualizações, leia as instruções das mesmas! <br />
                            Algumas atualizações podem fazer com que seu site fique offline por alguns segundos. <br />
                            Durante as atualizações não utilize o sistema, não saia dessa página e não atualize a página.
                        </h4>

                        <br /><br />

                        <div class="alert alert-{_ALERT_}" id="alert-log">
                            {_INFO_}
                            {_LOG_}
                        </div>
                        <p class="text-center {_SHOW_BTN_UPDATE_}">
                            <button class="btn btn-warning" type="button" id="btn-oxy-update">
                                <i class="fa fa-exchange"></i>
                                Atualizar o sistema
                            </button>

                            <button class="btn hide" type="button" id="btn-wait-update"></button>
                        </p>
                    </div>
                </div>
            </div>                
        </div>                
    </div>
    <script src="assets/vendor/jquery-1.11.0.min.js" type="text/javascript"></script>
    <script src="assets/vendor/bootstrap-3.2.0/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="assets/js/admin/main.js" type="text/javascript"></script>
    <script type="text/javascript">setMenuAtivo('update');</script>
    <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.5.1.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdn.oesmith.co.uk/morris-0.5.1.min.js"></script>        
    <script type="text/javascript">
        $('#btn-oxy-update').on('click', function () {
            $('#alert-log').slideUp();
            $(this).hide();
            var url = '{BASEURI}/painel/update/atualizar/';
            $.post(url, {}, function (response) {
                //download
            });
            $('#btn-wait-update').removeClass('hide').show();
            $('#btn-wait-update').addClass('btn-primary').removeClass('btn-warning');
            //$('#btn-wait-update').attr('disabled','disabled');
            $('#btn-wait-update').html('<i class="fa fa-refresh fa-spin"></i> Baixando arquivos, aguarde...');
            $(function () {
                setTimeout(function () {
                    $('#btn-wait-update').html('<i class="fa fa-refresh fa-spin"></i> Não utilize o sistema até que o processo esteja finalizado...');
                }, 5000)
            });
            $(function () {
                setTimeout(function () {
                    $('#btn-wait-update').html('<i class="fa fa-refresh fa-spin"></i> Não atualize a tela, apenas aguarde... o sistema está baixando os arquivos');
                }, 15000)
            });
            getStatus();
        });

        function getStatus() {
            var url = '{BASEURI}/painel/update/finish/';
            $.post(url, {}, function (rs) {
                rs = $.parseJSON(rs);
                if (rs.finish == 'true') {
                    if (rs.error == 'true') {
                        //
                    } else {
                        if (rs.migrate == 'true') {
                            var murl = '{BASEURI}/painel/migrate/';
                            $.post(murl, {}, function (data) {
                                //
                            });
                        }
                    }
                    $('#btn-oxy-update').removeClass('btn-primary').addClass('btn-success').html('<i class="fa fa-check-circle-o"></i> Seu sistema foi atualizado!');
                    $(function () {
                        setTimeout(function () {
                            var furl = '{BASEURI}/painel/update/';
                            window.location = furl;
                        }, 5000);
                    });

                } else {
                    setTimeout(function () {
                        getStatus();
                    }, 15000);
                }
            })
        }
    </script>
</body>
</html>