<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="keywords" content="{SITE_KEYWORDS}">
        <meta name="author" content="{SITE_AUTOR}">
        <title>{SITE_TITLE} - {SITE_SLOGAN}</title>
        <link rel='stylesheet' type='text/css' href='{SITE_TEMPLATE}/css/bootstrap.min.css'>
        <link rel="stylesheet" href="{BASEURI}/assets/vendor/font-awesome/css/font-awesome.min.css">
        <link rel='stylesheet' type='text/css' href="{SITE_TEMPLATE}/css/main.css?v=<?=date('dmyhis')?>">
        <link href="{BASEURI}/assets/vendor/fakeinput/fakeinput.css" rel="stylesheet" type="text/css">
        <script src="{SITE_TEMPLATE}/js/jquery.js"></script>
        <script src="{SITE_TEMPLATE}/js/bootstrap.min.js"></script>
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <?php require_once 'top_bar.phtml'; ?>
        <?php require_once 'top_menu.phtml'; ?>

        <div class="container">
            <div class="row">
                <div class="col-md-9">

                    <div class="main_content">
                        <h3 class="title"><span class="pull-left">CADASTRE-SE E COMECE A APARECER</span></h3>
                        <br />
                        <div class="">
                            <form action="{BASEURI}/cadastro/atualizar/" enctype="multipart/form-data"
                                  role="form" method="post" id="form-cliente" >

                                <div class="form-group well well-sm">
                                    <label for="cliente_grupo">Categorias</label>
                                    <select name="cliente_grupo" id="cliente_grupo" class="form-control" required>
                                        <option value="">Selecione uma categoria...</option>
                                        <?php if ($this->isMod('cliente')): ?>
                                            <?php if (isset($this->modulo['cliente']['menu-lista'])): ?>
                                                <?php foreach ($this->modulo['cliente']['menu-lista'] as $s): ?>
                                                    <option value="<?= $s->grupo_id ?>"><?= $s->grupo_nome ?></option>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </select>
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_empresa">Nome da Empresa</label>
                                    <input type="text" name="cliente_empresa" id="cliente_empresa" class="form-control" placeholder="Informe o nome da empresa" maxlength="30" required/>
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_nome">Slogan (opcional - até 150 caracteres)</label>
                                    <input type="text" name="cliente_nome" id="cliente_nome" class="form-control"
                                           placeholder="Informe o nome do contato" maxlength="150" />
                                </div>

                                <h3 class="title"><span class="pull-left">DADOS DE CONTATO</span></h3>
                                <br />

                                <div class="form-group well well-sm">
                                    <label for="cliente_fone">Telefone 01</label>
                                    <input type="text" name="cliente_fone" id="cliente_fone" class="fone form-control" placeholder="Informe um número de telefone"  required/>
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_fone2">Telefone 02</label>
                                    <input type="text" name="cliente_fone2" id="cliente_fone2" class="fone form-control" placeholder="Informe um número de telefone" />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_site">Site</label>
                                    <input type="text" name="cliente_site" id="cliente_site" class="form-control" placeholder="Informe o link do site ex: www.seusite.com.br" />
                                </div>

                                <h3 class="title"><span class="pull-left">ENDEREÇO E LOCALIZAÇÃO</span></h3>
                                <br />
                                <div class="form-group well well-sm">
                                    <label for="cliente_cep">CEP </label>
                                    <span class="pull-right"><small> <i class="fa fa-info-circle"></i> Ao informar seu cep, o sistema tentará preencher automaticamente seu endereço.</small></span>
                                    <input type="text" name="cliente_cep" id="cliente_cep" class="cep form-control"  required
                                           placeholder="Informe o cep do local" />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_endereco">Endereço</label>
                                    <input type="text" name="cliente_endereco" id="cliente_endereco" class="form-control"  required
                                           placeholder="Informe o endereço ex: Avenida Brasil" />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_num">Número</label>
                                    <input type="text" name="cliente_num" id="cliente_num" class="form-control"
                                           placeholder="Informe o número do local ex: 100"  required />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_complemento">Complemento</label>
                                    <input type="text" name="cliente_complemento" id="cliente_complemento" class="form-control"
                                           placeholder="Informe o complemento ex: 10º Andar - Sala 2 " />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_bairro">Bairro</label>
                                    <input type="text" name="cliente_bairro" id="cliente_bairro" class="form-control"
                                           placeholder="Informe o bairro"  required />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_cidade">Cidade</label>
                                    <input type="text" name="cliente_cidade" id="cliente_cidade" class="form-control"
                                           placeholder="Informe o endereço completo ex: Macaíba"   required />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_uf">UF/Estado</label>
                                    <select class="form-control" name="cliente_uf" id="cliente_uf">
                                        <option value="AC">AC</option>
                                        <option value="AL">AL</option>
                                        <option value="AM">AM</option>
                                        <option value="AP">AP</option>
                                        <option value="BA">BA</option>
                                        <option value="CE">CE</option>
                                        <option value="DF">DF</option>
                                        <option value="ES">ES</option>
                                        <option value="GO">GO</option>
                                        <option value="MA">MA</option>
                                        <option value="MG">MG</option>
                                        <option value="MS">MS</option>
                                        <option value="MT">MT</option>
                                        <option value="PA">PA</option>
                                        <option value="PB">PB</option>
                                        <option value="PE">PE</option>
                                        <option value="PI">PI</option>
                                        <option value="PR">PR</option>
                                        <option value="RJ">RJ</option>
                                        <option value="RN">RN</option>
                                        <option value="RO">RO</option>
                                        <option value="RR">RR</option>
                                        <option value="RS">RS</option>
                                        <option value="SC">SC</option>
                                        <option value="SE">SE</option>
                                        <option value="SP">SP</option>
                                        <option value="TO">TO</option>
                                    </select>
                                </div>

                                <h3 class="title"><span class="pull-left">LOGOMARCA E DESCRIÇÃO BREVE DOS SERVIÇOS PRESTADOS</span></h3>
                                <br />

                                <div class="form-group form-inline well well-sm">
                                    <label>Logo do Cliente </label>
                                    <span class="pull-right"><small> <i class="fa fa-info-circle"></i> Escolha uma imagem bonita, acredite, isso faz grande diferença.</small></span>
                                    <div class="fakeipt">
                                        <div class="uploader black">
                                            <input type="text" class="filename" readonly="readonly"/>
                                            <input type="button" name="file" id="file" class="button" value="Selecionar Imagem"/>
                                            <input type="file" name="filedata" id="filedata" size="30"/>
                                        </div>
                                        <div class="pull-right hide" id="slide-preview">
                                            <img src="{BASEURI}/midia/cliente/nopic.png" class="img-thumbnail" style="margin-top: -25px;width:140px; height: 75px;"/>
                                        </div>
                                    </div>
                                </div>


                                <div class="form-group well well-sm">
                                    <label for="cliente_nome">Palavras-chave (separadas por vírgula ex: pizza,drogaria,imóveis...)</label>
                                    <span class="pull-right"><small> <i class="fa fa-info-circle"></i> Essas palavras são utilizadas para localizar sua empresa nas buscas.</small></span>
                                    <input type="text" name="cliente_meta_keywords" id="cliente_meta_keywords" class="form-control" placeholder="Palavras-chave são utilizadas para lhe encontrar nas buscas ex: imóveis,pizzaria,drogaria,oficina" maxlength="150" required />
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_info">Descrição (máximo 1000 caracteres)</label>
                                    <textarea name="cliente_info" id="cliente_info"  rows="8" class="form-control"
                                              placeholder="Descrição dos serviços prestados" maxlength="1000" required></textarea>
                                </div>

                                <h3 class="title"><span class="pull-left">DADOS DE ACESSO</span></h3>
                                <br />

                                <div class="form-group well well-sm">
                                    <label for="cliente_email">E-mail</label>
                                    <input type="email" name="cliente_email" id="cliente_email" class="form-control" placeholder="Informe um endereço de e-mail"  required/>
                                </div>

                                <div class="form-group well well-sm">
                                    <label for="cliente_senha">Senha</label>
                                    <span class="pull-right text-uppercase"><small> <a href="javascript:void(0);" id="btn-show-pass"><i class="fa fa-asterisk"></i> Exibir a senha</a></small></span>
                                    <div id="div-pass">
                                        <input type="password" name="cliente_senha" id="cliente_senha" class="form-control" placeholder="Informe uma senha de acesso"  pattern=".{6,}" minlength="6" required/>
                                    </div>
                                </div>
                                <div>
                                    <p class="text-right">
                                        <button type="submit" class="btn btn-primary" id="btn-add-update"><i class="fa fa-check-circle"></i> <span id="btn-add-update-cliente">CADASTRAR</span></button>
                                        <button type="button" class="btn btn-danger hide" id="btn-add-update-cancel"><i class="fa fa-times-circle-o"></i> <span>Cancelar</span></button>
                                    </p>
                                </div>
                                <input type="hidden" name="cliente_id" id="cliente_id"  value=""/>
                            </form>
                        </div>
                    </div>
                </div>
                <?php require_once 'right_bar.phtml'; ?>
            </div>
        </div>

        <?php require_once 'rodape.phtml'; ?>
        <script type="text/javascript">
            $(function () {
                $('#top-menu-cadastro').addClass('active');
                $('[data-toggle="tooltip"]').tooltip();
                $('#cliente_cep').mask('99999-999');
                $('.fone').mask('(99) 9999-99990');
                $('#cliente_cep').on('change', function () {
                    var url = '{BASEURI}/cep/getcep/?cep=' + $.trim($(this).val());
                    $.getJSON(url, {}, function (data) {
                        if (data != -1) {
                            $('#cliente_endereco').val(data.rs[0].endereco);
                            $('#cliente_bairro').val(data.rs[0].bairro);
                            $('#cliente_cidade').val(data.rs[0].cidade);
                            $('#cliente_uf').val(data.rs[0].uf);
                            $('#cliente_num').focus();
                        }
                    });
                });
                $('#btn-show-pass').toggle(function () {
                    var senha = $('#cliente_senha').val();
                    $('#cliente_senha').remove();
                    $('<input />')
                            .addClass('form-control')
                            .attr('type', 'text')
                            .attr('placeholder', 'Informe uma senha para sua conta')
                            .attr('name', 'cliente_senha')
                            .attr('id', 'cliente_senha')
                            .val(senha)
                            .appendTo($('#div-pass'));
                }, function () {
                    var senha = $('#cliente_senha').val();
                    $('#cliente_senha').remove();
                    $('<input />')
                            .addClass('form-control')
                            .attr('type', 'password')
                            .attr('placeholder', 'Informe uma senha para sua conta')
                            .attr('name', 'cliente_senha')
                            .attr('id', 'cliente_senha')
                            .val(senha)
                            .appendTo($('#div-pass'));
                }
                );
            });
        </script>
        <script src="{BASEURI}/assets/vendor/jquery.mask.min.js" type="text/javascript"></script>
        <script src="{BASEURI}/assets/vendor/fakeinput/fakeinput.js" type="text/javascript"></script>

        <?php require_once('imguploader_div.phtml'); ?>
        <?php require_once('imguploaderview_div.phtml'); ?>

    </body>
</html>
