<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{SITE_DESCRIPTION}">
        <meta name="keywords" content="{SITE_KEYWORDS}">
        <meta name="author" content="{SITE_AUTOR}">
        <?php if (isset($this->data['cliente']->{'cliente_nome'})): ?>
            <title><?= $this->data['cliente']->{'cliente_empresa'} ?> - <?= $this->data['cliente']->{'cliente_nome'} ?>  | <?= $this->data['cliente']->{'grupo_nome'} ?> em {SITE_TITLE}</title>
        <?php else: ?>
            <title> {SITE_TITLE} - {SITE_SLOGAN}</title>
        <?php endif; ?>
        <link rel='stylesheet' type='text/css' href='{SITE_TEMPLATE}/css/bootstrap.min.css'>
        <link rel='stylesheet' type='text/css' href='{SITE_TEMPLATE}/css/owl.carousel.css'>
        <link rel='stylesheet' type='text/css' href='{SITE_TEMPLATE}/css/owl.theme.css'>
        <link rel="stylesheet" href="{SITE_BASEURI}/assets/vendor/font-awesome/css/font-awesome.min.css">
        <link rel='stylesheet' type='text/css' href="{SITE_TEMPLATE}/css/main.css?v=<?= date('dmyhis') ?>">
        <!--[if lt IE 9]>
        <script src="assets/js/html5shiv.js"></script>
        <script src="assets/js/respond.min.js"></script>
        <![endif]-->
        <script src="{SITE_TEMPLATE}/js/jquery.js"></script>
    </head>
    <body>
        <?php require_once 'top_bar.phtml'; ?>
        <?php require_once 'top_menu.phtml'; ?>
        <div class="container">
            <div class="row">
                <div class="col-md-9">
                    <?php require_once 'top_busca.phtml'; ?>
                    <div class="main_content">
                        <?php if ($this->isMod('cliente')): ?>
                            <?php if (isset($this->data['cliente']->{'cliente_nome'})): ?>
                                <div class="detail-product">
                                    <h3 class="title"><?= $this->data['cliente']->{'cliente_empresa'} ?> - <?= $this->data['cliente']->{'cliente_nome'} ?></h3>
                                    <div class="row">
                                        <div class="col-md-4">
                                            <img src="{SITE_BASEURI}/thumb.php?zc=2&h=200&w=250&src=<?= Imagem:: get("midia/cliente", $this->data['cliente']->{'cliente_logo'}) ?>" alt="logo - <?= $this->data['cliente']->{'cliente_nome'} ?>" class="img-responsive">
                                        </div>
                                        <div class="col-md-8">
                                            <h3 class="title no-margin-t">CONTATO</h3>
                                            <div class="well well-sm">
                                                <p>
                                                    <?php if ($this->data['cliente']->{'cliente_fone'} != ""): ?>
                                                        <i class="fa fa-phone-square"></i>
                                                        <?= $this->data['cliente']->{'cliente_fone'} ?>
                                                        <?php if ($this->data['cliente']->{'cliente_fone2'} != ""): ?>
                                                            / <?= $this->data['cliente']->{'cliente_fone2'} ?>
                                                        <?php endif; ?>
                                                        <?php if ($this->data['cliente']->{'cliente_fone3'} != ""): ?>
                                                            / <?= $this->data['cliente']->{'cliente_fone3'} ?>
                                                        <?php endif; ?>
                                                        <br/>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_email'} != ""): ?>
                                                        <i class="fa fa-envelope"></i>
                                                        <a href="#myModal" role="button" data-toggle="modal">
                                                            <?= $this->data['cliente']->{'cliente_email'} ?>
                                                        </a>
                                                        <br/>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_site'} != ""): ?>
                                                        <i class="fa fa-globe"></i>
                                                        <a href="<?= $this->data['cliente']->{'cliente_site'} ?>" target="_blank">
                                                            <?= $this->data['cliente']->{'cliente_site'} ?></a>
                                                    <?php endif; ?>
                                                </p>
                                                <p class="text-right">
                                                    <?php if ($this->data['cliente']->{'cliente_fb'} != ""): ?>
                                                        <a href="<?= $this->data['cliente']->{'cliente_fb'} ?>" target="_blank" title="siga-nos no facebook">
                                                            <img src="{SITE_BASEURI}/assets/images/social/fb_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_tw'} != ""): ?>
                                                        <a href="<?= $this->data['cliente']->{'cliente_tw'} ?>" target="_blank"  title="siga-nos no twitter">
                                                            <img src="{SITE_BASEURI}/assets/images/social/tw_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_in'} != ""): ?>
                                                        <a href="<?= $this->data['cliente']->{'cliente_in'} ?>" target="_blank"  title="siga-nos no instagram">
                                                            <img src="{SITE_BASEURI}/assets/images/social/in_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_gp'} != ""): ?>
                                                        <a href="<?= $this->data['cliente']->{'cliente_gp'} ?>" target="_blank"  title="siga-nos no google+">
                                                            <img src="{SITE_BASEURI}/assets/images/social/gp_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_lk'} != ""): ?>
                                                        <a href="<?= $this->data['cliente']->{'cliente_lk'} ?>" target="_blank"  title="siga-nos no linkedin">
                                                            <img src="{SITE_BASEURI}/assets/images/social/lk_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($this->data['cliente']->{'cliente_sk'} != ""): ?>
                                                        <a href="javascript:void(0);" title="chame-nos no skype: <?= $this->data['cliente']->{'cliente_sk'} ?>">
                                                            <img src="{SITE_BASEURI}/assets/images/social/sk_32.png" />
                                                        </a>
                                                    <?php endif; ?>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <br/>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <ul class="nav nav-tabs" id="myTab">
                                                <li class="active">
                                                    <a href="#info" class="text-uppercase" data-toggle="tab">
                                                        <i class="fa fa-info-circle"></i>
                                                        sobre  nós
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#dados" class="text-uppercase" data-toggle="tab">
                                                        <i class="fa fa-map-marker"></i>
                                                        onde estamos
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="#contato" class="text-uppercase" data-toggle="tab">
                                                        <i class="fa fa-envelope"></i>
                                                        entre em contato
                                                    </a>
                                                </li>
                                            </ul>
                                            <div class="tab-content">
                                                <div class="tab-pane active" id="info" style="padding-top: 10px">
                                                    <div class="div-info">
                                                        <?= $this->data['cliente']->{'cliente_info'} ?>
                                                    </div>
                                                    <br /><br />

                                                    <address class="hide">
                                                        <?= $this->data['cliente']->{'cliente_endereco'} ?>,
                                                        <?= $this->data['cliente']->{'cliente_num'} ?> -
                                                        <?= $this->data['cliente']->{'cliente_complemento'} ?>,
                                                        <?= $this->data['cliente']->{'cliente_bairro'} ?>,
                                                        <?= $this->data['cliente']->{'cliente_cidade'} ?> -
                                                        <?= $this->data['cliente']->{'cliente_uf'} ?>
                                                    </address>

                                                    <br /><br />
                                                </div>
                                                <div class="tab-pane" id="dados">
                                                    <div style="padding: 10px;">
                                                        <div id="gmap" class="gmap"  style="width: 100%;height:400px;"></div>
                                                        <br /><br />
                                                    </div>
                                                </div>
                                                <div class="tab-pane" id="contato">
                                                    <div style="padding: 10px">
                                                        <br /><br />
                                                        <h4>Entre em contato com <?= $this->data['cliente']->{'cliente_empresa'} ?>, preenchendo o formulário abaixo!</h4>
                                                        <br />
                                                        <form id="form-contato-cliente" name="form-contato-cliente" role="form" method="POST" onsubmit="return false">
                                                            <div class="form-group">
                                                                <label>Nome: </label>
                                                                <input type="text" class="form-control" name="contato_nome" id="contato_nome" placeholder="Informe seu nome"  />
                                                            </div>
                                                            <div class="form-group">
                                                                <label>E-mail: </label>
                                                                <input type="email" class="form-control" name="contato_email" id="contato_email" placeholder="Informe uma conta de e-mail válida"/>
                                                            </div>
                                                            <div class="form-group">
                                                                <label>Telefone: </label>
                                                                <input type="text" class="form-control fone" name="contato_fone" id="contato_fone" placeholder="DDD + Telefone"  />
                                                            </div>
                                                            <div class="form-group">
                                                                <textarea class="form-control" rows="5" name="contato_mensagem" id="contato_mensagem" placeholder="Digite aqui  sua mensagem..."></textarea>
                                                            </div>
                                                            <div class="form-group">
                                                                <button type="submit" class="btn btn-primary" id="btn-contato-enviar">
                                                                    <i class="fa fa-send"></i>
                                                                    Enviar Mensagem
                                                                </button>
                                                            </div>
                                                            <input type="hidden" name="contato_cliente_email" id="contato_cliente_email"  value="<?= $this->data['cliente']->{'cliente_email'} ?>" />
                                                            <input type="hidden" name="contato_link" id="contato_link"  value="{SITE_BASEURI}/<?= $this->data['cliente']->{'cliente_email'} ?>" />
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </div>
                <?php require_once 'right_bar.phtml'; ?>
            </div>
        </div>

        <script src="{SITE_TEMPLATE}/js/bootstrap.min.js"></script>
        <script src="{SITE_TEMPLATE}/js/respond.min.js"></script>

        <?php require_once 'rodape.phtml'; ?>
        <script src="{SITE_BASEURI}/assets/vendor/jquery.mask.min.js" type="text/javascript"></script>
        <script type="text/javascript">
            $(function () {
                baseUri = '{SITE_BASEURI}';
                $('.fone').mask('(99) 9999-99990');
            });
        </script>
        <script src="{SITE_TEMPLATE}/js/contato.js"></script>
        <!--
        <script src="{SITE_TEMPLATE}/js/jquery.fancybox.js"></script>
        <script src="{SITE_TEMPLATE}/js/owl.carousel.min.js"></script>
        <script>
            $(function () {
                 $('.thumbnail').fancybox({
                 openEffect: 'none',
                 closeEffect: 'none'
                 });
                 $('.carousel').carousel({
                 interval: false
                 });

                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        -->
        <script>
            $(function () {
                $('#myTab a:first').tab('show');
                $('#myTab a').click(function (e) {
                    e.preventDefault();
                    $(this).tab('show');
                });
                $('[data-toggle="tooltip"]').tooltip();
            });
        </script>
        <?php if ($this->data['cliente']->{'cliente_lat_lon'} != ""): ?>
            <?php require_once 'detalhe_mapa.phtml'; ?>
        <?php endif; ?>

        <?php
        if (isset($this->data['checkvalues'])){
          echo "<h2> HELLO WORLD xD </h2>";
        }
        ?>
    </body>
</html>
