<div id="imguploader">
  <script>
  // Initialise DropZone form control
  // dropzoneForm = the id of your dropzone form
  $(document).ready(function(){
    Dropzone.options.dropzoneform = {
        maxFilesize: 10, // Mb
        init: function () {
            // Set up any event handlers
            this.on('queuecomplete', function () {
                window.location = 'http://localhost/guiafacil/cadastro';
            });
        }
    };
  });
  </script>
  <form action="{BASEURI}/ImageUploader/doImageUpload" class="dropzone" id="dropzoneform"></form>
</div>
