<div id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4 class="">Minha Conta</h4>
                <ul>
                    <li><a href="#">Entrar</a></li>
                    <li><a href="#">Cadastro</a></li>
                </ul>
            </div>

            <?php if (isset($this->data['area'])): ?>
                <?php foreach ($this->data['area'] as $a): ?>
                    <?php if (isset($a->{'PAG'}[0])): ?>
                        <!-- Column -->
                        <?php if ($a->area_footer == 1): ?>
                            <div class="col-md-3">
                                <h4><?= $a->area_nome ?></h4>
                                <ul class="links underline">
                                    <?php foreach ($a->{'PAG'} as $p): ?>
                                        <li>
                                            <a href="{SITE_BASEURI}/pagina/<?= $a->area_url ?>/<?= $p->pagina_url ?>/<?= $p->pagina_id ?>/"><?= $p->pagina_nome ?></a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <!-- Column /END -->
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endforeach; ?>
            <?php endif; ?>

            <div class="hide">
                <p>
                    <a href="#"><img src="{SITE_TEMPLATE}/img/social-facebook.png" alt="Facebook"/></a>
                    <a href="#"><img src="{SITE_TEMPLATE}/img/social-twitter.png" alt="Twitter"/></a>
                    <a href="#"><img src="{SITE_TEMPLATE}/img/social-rss.png" alt="RSS"/></a>
                    <a href="#"><img src="{SITE_TEMPLATE}/img/social-flickr.png" alt="Flickr"/></a>
                </p>
            </div>
        </div>
    </div>
</div>