<div id="top-bar">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <a class="brand pull-left" href="{SITE_BASEURI}/"><img src="{SITE_BASEURI}/midia/layout/{SITE_LOGO}?v=<?= rand(1, 25) ?>" style="z-index: 999;margin-top:{SITE_LOGO_Y}px !important;margin-left:{SITE_LOGO_X}px !important;" alt="logo - {SITE_TITLE}" title="{SITE_TITLE}"></a>
                <ul class="nav nav-pills pull-right">

                </ul>									
            </div>
        </div>
    </div>
</div>	